### ISSUE TITLE
Local link resolution not working when using Markdown syntax

### ISSUE THREAD

**Issue by mderriey** [JimBobSquarePants/umbmarkdown#4]
Hi there 👋,

Thanks for the great library, we've been using it and it's really nice being able to use GHfM, not to mention the handy link and media pickers!

We found that local links &mdash; like `localLink:umb://document/<udi>` &mdash; are not being translated when used with the Markdown link syntax &mdash; `[<link-text>](<link-url>)`.

It boils down to the fact that the built-in function that takes care of the translation ([`TemplateUtilities.ParseInternalLinks`](https://github.com/umbraco/Umbraco-CMS/blob/89f69bd2a80810c2ff6fc38736ed398c48652327/src/Umbraco.Web/Templates/TemplateUtilities.cs#L39-L78)) uses a [regular expression](https://github.com/umbraco/Umbraco-CMS/blob/89f69bd2a80810c2ff6fc38736ed398c48652327/src/Umbraco.Web/Templates/TemplateUtilities.cs#L98-L100) that matches `href` attributes only.

Since the Markdown links don't match this pattern, the local links are rendered as-is on the pages.

A potential solution we're seeing is calling the same utility functions after the Markdown content has been transpiled to HTML in the [`ConvertSourceToObject`](https://github.com/JimBobSquarePants/umbmarkdown/blob/4d54f96be7837c968b834e2cd7ba628983964c25/src/UmbMarkdown/UmbMarkdownPropertyValueConverter.cs#L54-L57) function in the property value converter.

Would that be fine with you? If so, more than happy to open a PR for that.

Cheers 👍

**Comment by JimBobSquarePants** [comment]
Aw nice! It's good to see someone actually using this. I tried to get the core Umbraco team interested but they weren't so I haven't touched it in ages. 

That sounds like a good fix so yeah, a PR would be great! 👍
